# Generated by Django 5.0.6 on 2024-07-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e4data', '0002_analisisfrecuenciacardiaca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='analisisfrecuenciacardiaca',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e4data.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisistemperatura',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='e4data.usuario'),
            preserve_default=False,
        ),
    ]
