# Generated by Django 5.0.6 on 2024-07-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e4data', '0003_rename_tiempo_inicial_analisisacelerometro_inicio_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
