# Generated by Django 5.0.6 on 2024-07-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e4data', '0004_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
